### ISSUE TITLE
NFL Preseason stats 

### ISSUE THREAD

**Issue by eliavWiseData** [nflverse/nflverse-data#45] opened 2024-07-17 12:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It's not a problem rather than a request to add more impactful data 

### Describe the solution you'd like

Look for the preseason data from the same sources 

### Describe alternatives you've considered

Other sites doesn't provide such detailed data as the PBP

**Comment by john-b-edwards** [comment] 2024-08-05 05:07
Closed, duplicate of #32

**Closed by john-b-edwards** 2024-08-05 05:07 UTC
