### ISSUE TITLE
Kickoff_Distance only showing value for runbacks.

### ISSUE THREAD

**Issue by Cityviewsound** [nflverse/nflverse-data#18] opened 2022-10-25 00:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.0.2

### Describe the bug

In PBP.. Kick_Distance only shows a value when the kickoff is not a touchback. please show a value for all kickoffs. If the kickoff starts On the 35, and the kick is a touchback, the kick distance would be 50 yards.

### Reprex

```r
Using the pbp releases.
```

### Expected Behavior

If the kickoff starts On the 35, and the kick is a touchback, the kick distance would be 50 yards.

### nflverse_sitrep

```r
N/A
```

### Screenshots

```markdown
N/A
```

### Additional context

N/A

**Comment by tanho63** [comment] 2022-10-25 00:56
duplicate of nflverse/nflfastR#392.

**Closed by tanho63** 2022-10-25 00:56 UTC
